import json
from pathlib import Path
from typing import Any, Dict, List, Tuple

from src import config

class VectorWriter:
    """Handles parsing inference outputs and retrieving spatial metadata for georeferencing."""

    def __init__(self, manifest_filename: str = config.MANIFEST_FILENAME):
        # Uses config paths strictly to maintain air-gapped portability
        self.manifest_path = config.INTERIM_DIR / manifest_filename
        self.tile_metadata = self._load_manifest()

    def _load_manifest(self) -> Dict[str, Any]:
        """
        Core Function 2: Retrieve Spatial Metadata.
        Reads the manifest.json generated by the chipper to map tile filenames 
        to their specific 6-parameter Affine transforms and CRS.
        """
        if not self.manifest_path.exists():
            raise FileNotFoundError(f"Manifest not found at {self.manifest_path}")

        with open(self.manifest_path, "r", encoding="utf-8") as f:
            manifest = json.load(f)

        # Create a fast O(1) lookup dictionary keyed by tile filename
        metadata_lookup = {
            tile["filename"]: {
                "transform": tile["transform"],
                "crs": manifest["crs"],
                "source_raster": manifest["source_raster"]
            }
            for tile in manifest["tiles"]
        }
        
        return metadata_lookup

    def parse_inference_outputs(
        self, 
        tile_filename: str, 
        bounding_boxes: List[Tuple[float, float, float, float]], 
        labels: List[str], 
        scores: List[float]
    ) -> List[Dict[str, Any]]:
        """
        Core Function 1: Parse Inference Outputs.
        Receives local pixel bounding boxes [x_min, y_min, x_max, y_max] from offline VLMs 
        (Florence-2/Grounding DINO) and pairs them with the correct spatial metadata.
        """
        if tile_filename not in self.tile_metadata:
            raise ValueError(f"Metadata for {tile_filename} not found in manifest.")

        tile_spatial_data = self.tile_metadata[tile_filename]
        parsed_detections = []

        for bbox, label, score in zip(bounding_boxes, labels, scores):
            parsed_detections.append({
                "tile_filename": tile_filename,
                "source_raster": tile_spatial_data["source_raster"],
                "local_bbox": bbox, # [x_min, y_min, x_max, y_max] relative to the 256x256 chip
                "label": label,
                "confidence": score,
                "transform": tile_spatial_data["transform"],
                "crs": tile_spatial_data["crs"]
            })

        return parsed_detections

    def _pixel_bbox_to_geo_polygon(
        self, bbox: List[float], transform_array: List[float]
    ) -> Polygon:
        """
        Core Functions 3 & 4: Coordinate Transformation and Geometry Construction.
        Converts a local [x_min, y_min, x_max, y_max] pixel bounding box into a geographic 
        Shapely Polygon using the tile's specific Affine transform.
        """
        x_min, y_min, x_max, y_max = bbox
        
        # Reconstruct the Affine object from the 6-parameter array in the manifest
        transform = Affine(*transform_array)
        
        # Transform pixel coordinates to real-world coordinates (EPSG/UTM)
        top_left = transform * (x_min, y_min)
        top_right = transform * (x_max, y_min)
        bottom_right = transform * (x_max, y_max)
        bottom_left = transform * (x_min, y_max)
        
        # Construct and return the spatial geometry
        return Polygon([top_left, top_right, bottom_right, bottom_left])

    

    def _format_geometry(self, geom: Polygon, label: str) -> Any:
        """
        Addition 3: Dynamic Geometry Typing.
        Converts polygons to centroids (Points) for discrete countable objects, 
        or retains them as Polygons for continuous infrastructure.
        """
        # Define target categories that should be strictly counted as points
        point_targets = ["tent", "aircraft", "helicopter", "vehicle"]
        
        if any(target in label.lower() for target in point_targets):
            return geom.centroid
        
        # For trenchlines, military compounds, or undefined targets, return the Polygon
        return geom

    def _apply_spatial_nms(
        self, features: List[Dict[str, Any]], iou_threshold: float = 0.4
    ) -> List[Dict[str, Any]]:
        """
        Addition 1: Geospatial Non-Maximum Suppression (NMS).
        Resolves duplicate overlapping geometries generated on tile boundaries 
        due to the inference stride parameter.
        """
        # Group features by label to ensure we only suppress identical classes
        grouped_features = {}
        for feat in features:
            grouped_features.setdefault(feat["label"], []).append(feat)

        nms_features = []

        for label, group in grouped_features.items():
            # Sort group by model confidence (descending)
            group = sorted(group, key=lambda x: x["confidence"], reverse=True)
            keep = []
            
            for current in group:
                should_keep = True
                current_geom = current["geometry"]
                
                for retained in keep:
                    retained_geom = retained["geometry"]
                    
                    # Optimization: Only compute intersection if bounding boxes overlap
                    if current_geom.intersects(retained_geom):
                        intersection_area = current_geom.intersection(retained_geom).area
                        union_area = current_geom.union(retained_geom).area
                        
                        # Calculate Intersection over Union (IoU)
                        iou = intersection_area / union_area if union_area > 0 else 0
                        
                        # If overlap exceeds threshold, suppress the lower-confidence detection
                        if iou > iou_threshold:
                            should_keep = False
                            break
                
                if should_keep:
                    keep.append(current)
            
            nms_features.extend(keep)
            
        return nms_features

    def export_to_vector(
        self, 
        parsed_detections: List[Dict[str, Any]], 
        prompt_used: str, 
        acquisition_date: str = "Unknown",
        output_filename: str = "detections.gpkg",
        iou_threshold: float = 0.4
    ) -> Path:
        """
        Core Function 5 (Updated): Standardized Export + Additions 1 & 2.
        Integrates spatial NMS, dynamic typing, and attribute enrichment (provenance) 
        before exporting to a GIS-ready format.
        """
        if not parsed_detections:
            print("No detections provided. Skipping export.")
            return None

        raw_features = []
        target_crs = parsed_detections[0]["crs"]

        for det in parsed_detections:
            raw_geom = self._pixel_bbox_to_geo_polygon(det["local_bbox"], det["transform"])
            
            # Apply dynamic geometry typing based on the label
            final_geom = self._format_geometry(raw_geom, det["label"])

            # Addition 2: Temporal & Provenance Attribute Enrichment
            raw_features.append({
                "geometry": final_geom,
                "label": det["label"],
                "confidence": det["confidence"],
                "prompt_used": prompt_used,                     # Crucial for methodology verification
                "acquisition_date": acquisition_date,           # Crucial for Timur's time-series tracking
                "source_raster": det["source_raster"],
                "tile_filename": det["tile_filename"]
            })

        # Apply Geospatial NMS to clean up overlapping boundary detections
        cleaned_features = self._apply_spatial_nms(raw_features, iou_threshold)

        # Construct GeoDataFrame
        gdf = gpd.GeoDataFrame(cleaned_features, crs=target_crs)
        
        output_path = config.PROCESSED_DIR / output_filename
        gdf.to_file(output_path, driver="GPKG")
        
        return output_path






