"""
Batch Inference Runner for Air-Gapped Vision-Language Models.
Orchestrates tile-by-tile detection execution across intermediate raster tiles,
manages GPU VRAM garbage collection, and exports tile-level prediction JSONs
formatted for RasterRebuilder.
"""

import gc
import json
import logging
from pathlib import Path
from typing import Any, Dict, List, Optional, Union

import torch
from tqdm import tqdm

from src import config

logger = logging.getLogger(__name__)


class BatchInferenceRunner:
    """
    Orchestrates batch inference over tiled imagery directories or chipping manifests.
    Executes VLM prediction, manages GPU memory cleanup, and persists individual
    detection outputs to disk.
    """

    def __init__(self, model_adapter: Any):
        """
        Initializes the runner with an instantiated model adapter or wrapper.

        Args:
            model_adapter: Instance of LocalVLMWrapper or GroundingDINOAdapter.
        """
        self.adapter = model_adapter

    def _clear_vram(self) -> None:
        """
        Forces Python garbage collection and clears CUDA cache to prevent
        out-of-memory errors during large batch processing runs.
        """
        gc.collect()
        if torch.cuda.is_available():
            torch.cuda.empty_cache()

    def run_on_manifest(
        self,
        manifest_path: Path,
        targets: Union[str, List[str]],
        output_dir: Optional[Path] = None,
        clear_vram_frequency: int = 10,
        **kwargs: Any,
    ) -> Path:
        """
        Executes inference on all tiles cataloged in a chipper manifest file.

        Args:
            manifest_path: Path to the JSON manifest generated by RasterChipper.
            targets: Plain-language prompt or list of target keys (e.g., 'tents', 'trenchlines').
            output_dir: Directory to store detection JSONs. Defaults to config.INTERIM_DIR / 'vlm_results'.
            clear_vram_frequency: Interval of processed tiles before explicitly flushing CUDA memory.
            **kwargs: Additional parameters passed to adapter predict method (e.g., box_threshold).

        Returns:
            Path to the directory containing tile-level output JSON files.
        """
        if not manifest_path.exists():
            raise FileNotFoundError(f"Manifest not found at {manifest_path}")

        with open(manifest_path, "r", encoding="utf-8") as f:
            manifest = json.load(f)

        tiles_info: List[Dict[str, Any]] = manifest.get("tiles", [])
        interim_tile_dir = config.INTERIM_DIR

        out_dir = output_dir or (config.INTERIM_DIR / "vlm_results")
        out_dir.mkdir(parents=True, exist_ok=True)

        logger.info(f"Starting batch inference over {len(tiles_info)} tiles.")

        for idx, tile_record in enumerate(tqdm(tiles_info, desc="VLM Tile Inference")):
            tile_path = interim_tile_dir / tile_record["filename"]
            json_filename = Path(tile_record["filename"]).with_suffix(".json")
            json_output_path = out_dir / json_filename

            if json_output_path.exists() and not config.DEFAULT_OVERWRITE:
                continue

            if not tile_path.exists():
                logger.warning(f"Tile image missing: {tile_path}. Skipping.")
                continue

            try:
                # Execute prediction via injected adapter interface
                results = self.adapter.predict(
                    image_data=tile_path,
                    targets=targets,
                    **kwargs,
                )

                # Persist raw detection dicts for RasterRebuilder.rebuild_vectors()
                with open(json_output_path, "w", encoding="utf-8") as jf:
                    json.dump(results, jf, indent=2)

            except Exception as e:
                logger.error(f"Error processing tile {tile_path.name}: {e}")
                continue

            # Routine GPU memory flushing
            if (idx + 1) % clear_vram_frequency == 0:
                self._clear_vram()

        self._clear_vram()
        logger.info(f"Batch inference complete. Results stored in {out_dir}")
        return out_dir

    def run_on_directory(
        self,
        input_dir: Path,
        targets: Union[str, List[str]],
        output_dir: Optional[Path] = None,
        file_extension: str = ".tif",
        clear_vram_frequency: int = 10,
        **kwargs: Any,
    ) -> Path:
        """
        Executes inference directly across an arbitrary directory of raster tiles.

        Args:
            input_dir: Directory containing tile images.
            targets: Prompt string or list of target keys.
            output_dir: Destination directory for JSON outputs.
            file_extension: Extension pattern to filter tile files.
            clear_vram_frequency: Interval of tiles before flushing CUDA cache.
            **kwargs: Additional parameters passed to adapter predict method.

        Returns:
            Path to destination directory containing output JSON files.
        """
        tile_paths = list(input_dir.glob(f"*{file_extension}"))
        out_dir = output_dir or (config.INTERIM_DIR / "vlm_results")
        out_dir.mkdir(parents=True, exist_ok=True)

        logger.info(f"Found {len(tile_paths)} tiles matching '{file_extension}' in {input_dir}")

        for idx, tile_path in enumerate(tqdm(tile_paths, desc="Directory Inference")):
            json_filename = tile_path.with_suffix(".json").name
            json_output_path = out_dir / json_filename

            if json_output_path.exists() and not config.DEFAULT_OVERWRITE:
                continue

            try:
                results = self.adapter.predict(
                    image_data=tile_path,
                    targets=targets,
                    **kwargs,
                )

                with open(json_output_path, "w", encoding="utf-8") as jf:
                    json.dump(results, jf, indent=2)

            except Exception as e:
                logger.error(f"Failed processing tile {tile_path.name}: {e}")
                continue

            if (idx + 1) % clear_vram_frequency == 0:
                self._clear_vram()

        self._clear_vram()
        logger.info(f"Directory processing finished. Output directory: {out_dir}")
        return out_dir